### ISSUE TITLE
Copyright needs updating

### ISSUE THREAD

**Issue by MissPotato** [OrionFive/MoreMechanoids#19]
While it doesn't really negatively impact you to have outdated copyright, it does expand protection by doing so.

**Comment by OrionFive** [comment]
Thanks for letting me know, but it's not necessary. To the contrary, the copyright should be dated to the first publication (which I didn't do). See [this](https://stackoverflow.com/a/2391555).

**Comment by OrionFive** [comment]
Also, copyright is implicit, so technically it's not needed. It's more of a reminder that it exists and that the author cares about it, or that the author has maybe officially registered their copyright. But that's U.S. only.

**Comment by MissPotato** [comment]
Oh cool, thank you for explaining this, sorry!
